[project]
name = "discrete-event-sim"
version = "0.1.0"
description = "Discrete event simulator prototype"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "frozendict>=2.4.7",
]

[tool.pyright]
typeCheckingMode = "standard"
reportUnusedFunction = false

